# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e81f143ae95120b40bcdde93a88cfcfafe5acea07cbb3a7adca6ec609567b32f899ceccbe87d0bd138a165de46efc0645a9c2db18ccfe1771f0a922dafd1d6fe

test:
  secret_key_base: 21ae3c6893eceb3845449f1b6852b19dd3546baff15234d0f2fa5f7c62be1156cdc08deac80352966cf28134ae08dcc619568ba97f7c256f2ffef343c7739b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
